import unittest
from test_publicos.test_00_peliculas_genero import TestPeliculasGenero
from test_publicos.test_01_personas_mayores import TestPersonasMayores
from test_publicos.test_02_funciones_fecha import TestFuncionesFecha
from test_publicos.test_03_titulo_mas_largo import TestTituloMasLargo
from test_publicos.test_04_normalizar_fechas import TestNormalizarFechas
from test_publicos.test_05_personas_reservas import TestPersonasReservas
from test_publicos.test_06_peliculas_en_base_al_rating import TestPeliculasEnBaseAlRating
from test_publicos.test_07_mejores_peliculas import TestMejoresPeliculas
from test_publicos.test_08_pelicula_genero_mayor_rating import TestPeliculaGeneroMayorRating
from test_publicos.test_09_fechas_funciones_pelicula import TestFechasFuncionesPelicula
from test_publicos.test_10_genero_mas_transmitido import TestGeneroMasTransmitido
from test_publicos.test_11_id_funciones_genero import TestIdFuncionesGenero
from test_publicos.test_12_butacas_por_funcion import TestButacasPorFuncion
from test_publicos.test_13_salas_de_pelicula import TestSalasDePelicula
from test_publicos.test_14_nombres_butacas_altas import TestNombresButacasAltas
from test_publicos.test_15_nombres_persona_genero_mayores import TestNombresPersonaGeneroMayores
from test_publicos.test_16_genero_comun import TestGeneroComun
from test_publicos.test_17_edad_promedio import TestEdadPromedio
from test_publicos.test_18_obtener_horarios_disponibles import TestObtenerHorariosDisponibles
from test_publicos.test_19_personas_no_asisten import TestPersonasNoAsisten
from test_publicos.test_20_saludar import TestSaludar
from test_publicos.test_21_verificar_informacion import TestVerificarInformacion
from test_publicos.test_22_dar_informacion import TestDarInformacion
from test_publicos.test_23_dar_informacion_aleatoria import TestDarInformacionAleatoria
from test_publicos.test_24_agregar_informacion import TestAgregarInformacion
from test_publicos.test_25_actualizar_informacion import TestActualizarInformacion
from test_publicos.test_26_eliminar_pelicula import TestEliminarPelicula
from test_publicos.test_elementos_prohibidos import revisar_comandos_prohibidos_todo_archivos

if __name__ == "__main__":
	revisar_comandos_prohibidos_todo_archivos()
	unittest.main(verbosity=2)
